# -*- coding: utf-8 -*-
"""src/rag/rag_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nLFvjaIu59LxySDJ5_FXxZOIgpzf0CZn
"""

import os
import json
from pathlib import Path

import faiss
import numpy as np

from sentence_transformers import SentenceTransformer
from openai import OpenAI


# ============================================================
# Configuration
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

CHUNKS_PATH = PROJECT_ROOT / "data" / "raw" / "processed" / "chunks.json"

EMBEDDING_MODEL_NAME = "multi-qa-MiniLM-L6-cos-v1"
GENERATION_MODEL = "gpt-5.6-luna"

DEFAULT_TOP_K = 5


SYSTEM_PROMPT = """
You are CertFlow, an internal Account Data Certification assistant.

Answer the user's question using only the provided context.

Rules:
- Do not use outside knowledge.
- Do not invent policies, procedures, requirements, or facts.
- If the context is insufficient, clearly say that the available documentation
  is insufficient to answer the question.
- Answer the question directly and concisely.
- Avoid adding unrelated policy details.
- Cite the supporting document and section.
"""


# ============================================================
# Load data
# ============================================================

def load_chunks(chunks_path=CHUNKS_PATH):
    """Load preprocessed knowledge-base chunks."""

    with open(chunks_path, "r", encoding="utf-8") as file:
        return json.load(file)


# ============================================================
# Retriever
# ============================================================

class DenseRetriever:
    """
    Dense semantic retriever using SentenceTransformers + FAISS.

    Selected during retrieval evaluation:
    multi-qa-MiniLM-L6-cos-v1 + FAISS
    """

    def __init__(
        self,
        chunks,
        model_name=EMBEDDING_MODEL_NAME
    ):
        self.chunks = chunks
        self.texts = [
            chunk["content"]
            for chunk in chunks
        ]

        self.model = SentenceTransformer(
            model_name
        )

        self.index = self._build_index()

    def _build_index(self):
        """Create normalized embeddings and FAISS cosine-similarity index."""

        embeddings = self.model.encode(
            self.texts,
            normalize_embeddings=True,
            show_progress_bar=False
        )

        embeddings = np.asarray(
            embeddings,
            dtype="float32"
        )

        index = faiss.IndexFlatIP(
            embeddings.shape[1]
        )

        index.add(embeddings)

        return index

    def retrieve(self, query, k=DEFAULT_TOP_K):
        """Return the top-k most relevant chunks."""

        query_embedding = self.model.encode(
            [query],
            normalize_embeddings=True
        )

        query_embedding = np.asarray(
            query_embedding,
            dtype="float32"
        )

        scores, indices = self.index.search(
            query_embedding,
            k=k
        )

        results = []

        for rank, idx in enumerate(
            indices[0],
            start=1
        ):
            chunk = self.chunks[idx]

            results.append({
                "rank": rank,
                "score": float(
                    scores[0][rank - 1]
                ),
                "chunk_id": chunk["chunk_id"],
                "document": chunk["metadata"]["title"],
                "section": chunk["metadata"]["section"],
                "content": chunk["content"],
            })

        return results


# ============================================================
# Context builder
# ============================================================

def build_context(retrieved_chunks):
    """Format retrieved chunks for the LLM prompt."""

    context_parts = []

    for i, chunk in enumerate(
        retrieved_chunks,
        start=1
    ):
        context_parts.append(
            f"""
Source {i}
Document: {chunk['document']}
Section: {chunk['section']}

{chunk['content']}
""".strip()
        )

    return "\n\n---\n\n".join(
        context_parts
    )


# ============================================================
# RAG pipeline
# ============================================================

class CertFlowRAG:
    """
    End-to-end CertFlow RAG pipeline.

    Query
        -> dense retrieval
        -> top-k chunks
        -> context construction
        -> GPT generation
        -> grounded answer + sources
    """

    def __init__(
        self,
        openai_api_key=None,
        generation_model=GENERATION_MODEL,
        top_k=DEFAULT_TOP_K
    ):
        self.chunks = load_chunks()

        self.retriever = DenseRetriever(
            self.chunks
        )

        self.top_k = top_k
        self.generation_model = generation_model

        api_key = (
            openai_api_key
            or os.getenv("OPENAI_API_KEY")
        )

        if not api_key:
            raise ValueError(
                "OPENAI_API_KEY is not set."
            )

        self.client = OpenAI(
            api_key=api_key
        )

    def generate_answer(
        self,
        query,
        k=None
    ):
        """
        Retrieve relevant context and generate
        a grounded answer.
        """

        k = k or self.top_k

        retrieved_chunks = (
            self.retriever.retrieve(
                query,
                k=k
            )
        )

        context = build_context(
            retrieved_chunks
        )

        user_prompt = f"""
User question:
{query}

Retrieved context:
{context}

Answer the question using only the retrieved context.
Include a Sources section with the supporting document
and section names.
"""

        response = self.client.responses.create(
            model=self.generation_model,
            instructions=SYSTEM_PROMPT,
            input=user_prompt
        )

        return {
            "query": query,
            "answer": response.output_text,
            "retrieved_chunks": retrieved_chunks
        }


# ============================================================
# Local test
# ============================================================

if __name__ == "__main__":

    rag = CertFlowRAG()

    question = (
        "What evidence is required before "
        "an account can be certified?"
    )

    result = rag.generate_answer(
        question
    )

    print("\nQUESTION")
    print("=" * 60)
    print(result["query"])

    print("\nANSWER")
    print("=" * 60)
    print(result["answer"])

    print("\nRETRIEVED SOURCES")
    print("=" * 60)

    for chunk in result["retrieved_chunks"]:
        print(
            chunk["rank"],
            round(chunk["score"], 4),
            chunk["document"],
            "→",
            chunk["section"]
        )